version = 1
SPDX-PackageName = "kontrast"
SPDX-PackageSupplier = "Carl Schwan <carlschwan@kde.org>"

[[annotations]]
path = ["android/res/**/**.png", "android/**/**.xml", "android/ic_launcher-playstore.png", "org.kde.kontrast.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Carl Schwan <carlschwan@kde.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ".flatpak-manifest.json"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2022 Aleix Pol <aleixpol@kde.org>,", "2223 Jonah Brüchert <jbb@kaidan.im>"]
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

